# "test" suffix properties file. Scopes name samples: "test", "web-test", "api-test", etc.
# Overrides application.yml default properties


spring:
  datasource:
    url: jdbc:mysql://proxysql.master.meliseginf.com:6612/g2frescoDB?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

