# Properties file for local/dev environment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  datasource:
    host: 127.0.0.1:3306
    db: g2frescodb
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASS}
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
